[package]
name = "hosted_db_runner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = { version = "0.30.0" }
serde = { version = "1.0", features = ["derive"] }
